    name: secrets
    on: 
        - push
    jobs:
        secret:
            runs-on: ubuntu-latest
            steps:
                - name: using github secret
                  run: |
                    echo "secret: ${{secrets.MY_SECRET}}"
                    echo "variable: ${{vars.LOGISTIC_MODEL}}"